

ALUMINUM_STANDARDS = {

    "AA7075": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.50,               "unit": "%"},
        "Cu" : {"min": 1.20, "max": 2.00,  "unit": "%"},
        "Mn" : {"max": 0.30,               "unit": "%"},
        "Mg" : {"min": 2.10, "max": 2.90,  "unit": "%"},
        "Cr" : {"min": 0.18, "max": 0.28,  "unit": "%"},
        "Zn" : {"min": 5.10, "max": 6.10,  "unit": "%"},
        "Ti" : {"max": 0.20,               "unit": "%"},
        "Al" : {"min": 87.0,               "unit": "%"},
    },
    "AA6061": {
        "Si" : {"min": 0.40, "max": 0.80,  "unit": "%"},
        "Fe" : {"max": 0.70,               "unit": "%"},
        "Cu" : {"min": 0.15, "max": 0.40,  "unit": "%"},
        "Mn" : {"max": 0.15,               "unit": "%"},
        "Mg" : {"min": 0.80, "max": 1.20,  "unit": "%"},
        "Cr" : {"min": 0.04, "max": 0.35,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 95.0,               "unit": "%"},
    },
    "AA6063": {
        "Si" : {"min": 0.20, "max": 0.60,  "unit": "%"},
        "Fe" : {"max": 0.35,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"max": 0.10,               "unit": "%"},
        "Mg" : {"min": 0.45, "max": 0.90,  "unit": "%"},
        "Cr" : {"max": 0.10,               "unit": "%"},
        "Zn" : {"max": 0.10,               "unit": "%"},
        "Ti" : {"max": 0.10,               "unit": "%"},
        "Al" : {"min": 97.0,               "unit": "%"},
    },
    "AA2024": {
        "Si" : {"max": 0.50,               "unit": "%"},
        "Fe" : {"max": 0.50,               "unit": "%"},
        "Cu" : {"min": 3.80, "max": 4.90,  "unit": "%"},
        "Mn" : {"min": 0.30, "max": 0.90,  "unit": "%"},
        "Mg" : {"min": 1.20, "max": 1.80,  "unit": "%"},
        "Cr" : {"max": 0.10,               "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 90.0,               "unit": "%"},
    },
    "AA5052": {
        "Si" : {"max": 0.25,               "unit": "%"},
        "Fe" : {"max": 0.40,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"max": 0.10,               "unit": "%"},
        "Mg" : {"min": 2.20, "max": 2.80,  "unit": "%"},
        "Cr" : {"min": 0.15, "max": 0.35,  "unit": "%"},
        "Zn" : {"max": 0.10,               "unit": "%"},
        "Al" : {"min": 95.0,               "unit": "%"},
    },
    "AA5083": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.40,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"min": 0.40, "max": 1.00,  "unit": "%"},
        "Mg" : {"min": 4.00, "max": 4.90,  "unit": "%"},
        "Cr" : {"min": 0.05, "max": 0.25,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 92.0,               "unit": "%"},
    },
    "AA1100": {
        "Si+Fe": {"max": 0.95,             "unit": "%"},
        "Cu"   : {"max": 0.20,             "unit": "%"},
        "Mn"   : {"max": 0.05,             "unit": "%"},
        "Zn"   : {"max": 0.10,             "unit": "%"},
        "Al"   : {"min": 99.00,            "unit": "%"},
    },
    "AA3003": {
        "Si" : {"max": 0.60,               "unit": "%"},
        "Fe" : {"max": 0.70,               "unit": "%"},
        "Cu" : {"max": 0.20,               "unit": "%"},
        "Mn" : {"min": 1.00, "max": 1.50,  "unit": "%"},
        "Zn" : {"max": 0.10,               "unit": "%"},
        "Al" : {"min": 96.0,               "unit": "%"},
    },

    "EN-AW-7075": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.50,               "unit": "%"},
        "Cu" : {"min": 1.20, "max": 2.00,  "unit": "%"},
        "Mn" : {"max": 0.30,               "unit": "%"},
        "Mg" : {"min": 2.10, "max": 2.90,  "unit": "%"},
        "Cr" : {"min": 0.18, "max": 0.28,  "unit": "%"},
        "Zn" : {"min": 5.10, "max": 6.10,  "unit": "%"},
        "Ti" : {"max": 0.20,               "unit": "%"},
        "Al" : {"min": 87.0,               "unit": "%"},
    },
    "EN-AW-6061": {
        "Si" : {"min": 0.40, "max": 0.80,  "unit": "%"},
        "Fe" : {"max": 0.70,               "unit": "%"},
        "Cu" : {"min": 0.15, "max": 0.40,  "unit": "%"},
        "Mn" : {"max": 0.15,               "unit": "%"},
        "Mg" : {"min": 0.80, "max": 1.20,  "unit": "%"},
        "Cr" : {"min": 0.04, "max": 0.35,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 95.0,               "unit": "%"},
    },
    "EN-AW-6082": {
        "Si" : {"min": 0.70, "max": 1.30,  "unit": "%"},
        "Fe" : {"max": 0.50,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"min": 0.40, "max": 1.00,  "unit": "%"},
        "Mg" : {"min": 0.60, "max": 1.20,  "unit": "%"},
        "Cr" : {"max": 0.25,               "unit": "%"},
        "Zn" : {"max": 0.20,               "unit": "%"},
        "Ti" : {"max": 0.10,               "unit": "%"},
        "Al" : {"min": 95.0,               "unit": "%"},
    },
    "EN-AW-5083": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.40,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"min": 0.40, "max": 1.00,  "unit": "%"},
        "Mg" : {"min": 4.00, "max": 4.90,  "unit": "%"},
        "Cr" : {"min": 0.05, "max": 0.25,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 92.0,               "unit": "%"},
    },

    "JIS-A7075": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.50,               "unit": "%"},
        "Cu" : {"min": 1.20, "max": 2.00,  "unit": "%"},
        "Mn" : {"max": 0.30,               "unit": "%"},
        "Mg" : {"min": 2.10, "max": 2.90,  "unit": "%"},
        "Cr" : {"min": 0.18, "max": 0.28,  "unit": "%"},
        "Zn" : {"min": 5.10, "max": 6.10,  "unit": "%"},
        "Ti" : {"max": 0.20,               "unit": "%"},
        "Al" : {"min": 87.0,               "unit": "%"},
    },
    "JIS-A6061": {
        "Si" : {"min": 0.40, "max": 0.80,  "unit": "%"},
        "Fe" : {"max": 0.70,               "unit": "%"},
        "Cu" : {"min": 0.15, "max": 0.40,  "unit": "%"},
        "Mn" : {"max": 0.15,               "unit": "%"},
        "Mg" : {"min": 0.80, "max": 1.20,  "unit": "%"},
        "Cr" : {"min": 0.04, "max": 0.35,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 95.0,               "unit": "%"},
    },
    "JIS-A5083": {
        "Si" : {"max": 0.40,               "unit": "%"},
        "Fe" : {"max": 0.40,               "unit": "%"},
        "Cu" : {"max": 0.10,               "unit": "%"},
        "Mn" : {"min": 0.40, "max": 1.00,  "unit": "%"},
        "Mg" : {"min": 4.00, "max": 4.90,  "unit": "%"},
        "Cr" : {"min": 0.05, "max": 0.25,  "unit": "%"},
        "Zn" : {"max": 0.25,               "unit": "%"},
        "Ti" : {"max": 0.15,               "unit": "%"},
        "Al" : {"min": 92.0,               "unit": "%"},
    },
}

CARBON_STEEL_STANDARDS = {

    "SA516-70": {
        "Carbon"    : {"max": 0.28,  "unit": "%"},
        "Manganese" : {"max": 1.20,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.45,  "unit": "%"},
        "Yield Strength"  : {"min": 260.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 485.0, "max": 620.0, "unit": "MPa"},
        "Elongation"      : {"min":  17.0,              "unit": "%"},
    },
    "SA516-60": {
        "Carbon"    : {"max": 0.24,  "unit": "%"},
        "Manganese" : {"max": 1.05,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.45,  "unit": "%"},
        "Yield Strength"  : {"min": 220.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0, "max": 550.0, "unit": "MPa"},
        "Elongation"      : {"min":  21.0,              "unit": "%"},
    },
    "SA106-B": {
        "Carbon"    : {"max": 0.30,  "unit": "%"},
        "Manganese" : {"max": 1.06,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.10,  "unit": "%"},
        "Chromium"  : {"max": 0.40,  "unit": "%"},
        "Nickel"    : {"max": 0.40,  "unit": "%"},
        "Molybdenum": {"max": 0.15,  "unit": "%"},
        "Yield Strength"  : {"min": 240.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0,              "unit": "MPa"},
        "Elongation"      : {"min":  16.5,              "unit": "%"},
    },
    "SA106-C": {
        "Carbon"    : {"max": 0.35,  "unit": "%"},
        "Manganese" : {"max": 1.06,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.10,  "unit": "%"},
        "Yield Strength"  : {"min": 275.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 485.0,              "unit": "MPa"},
        "Elongation"      : {"min":  16.5,              "unit": "%"},
    },
    "A36": {
        "Carbon"    : {"max": 0.26,  "unit": "%"},
        "Manganese" : {"max": 1.05,  "unit": "%"},
        "Phosphorus": {"max": 0.04,  "unit": "%"},
        "Sulfur"    : {"max": 0.05,  "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Yield Strength"  : {"min": 250.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 400.0, "max": 550.0, "unit": "MPa"},
        "Elongation"      : {"min":  23.0,              "unit": "%"},
    },
    "A572-50": {
        "Carbon"    : {"max": 0.23,  "unit": "%"},
        "Manganese" : {"max": 1.35,  "unit": "%"},
        "Phosphorus": {"max": 0.04,  "unit": "%"},
        "Sulfur"    : {"max": 0.05,  "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Niobium"   : {"max": 0.05,  "unit": "%"},
        "Vanadium"  : {"max": 0.15,  "unit": "%"},
        "Yield Strength"  : {"min": 345.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 450.0,              "unit": "MPa"},
        "Elongation"      : {"min":  18.0,              "unit": "%"},
    },
    "SA213-T11": {
        "Carbon"    : {"max": 0.15,  "unit": "%"},
        "Manganese" : {"max": 0.60,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.025, "unit": "%"},
        "Silicon"   : {"max": 0.50,  "unit": "%"},
        "Chromium"  : {"min": 1.00, "max": 1.50, "unit": "%"},
        "Molybdenum": {"min": 0.44, "max": 0.65, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },
    "SA335-P11": {
        "Carbon"    : {"max": 0.15,  "unit": "%"},
        "Manganese" : {"max": 0.60,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.025, "unit": "%"},
        "Silicon"   : {"max": 0.50,  "unit": "%"},
        "Chromium"  : {"min": 1.00, "max": 1.50, "unit": "%"},
        "Molybdenum": {"min": 0.44, "max": 0.65, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },
    "SA335-P22": {
        "Carbon"    : {"max": 0.15,  "unit": "%"},
        "Manganese" : {"max": 0.60,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.025, "unit": "%"},
        "Silicon"   : {"max": 0.50,  "unit": "%"},
        "Chromium"  : {"min": 1.90, "max": 2.60, "unit": "%"},
        "Molybdenum": {"min": 0.87, "max": 1.13, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },
    "SA387-11": {
        "Carbon"    : {"max": 0.17,  "unit": "%"},
        "Manganese" : {"max": 0.65,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.50,  "unit": "%"},
        "Chromium"  : {"min": 1.00, "max": 1.50, "unit": "%"},
        "Molybdenum": {"min": 0.44, "max": 0.65, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 380.0,              "unit": "MPa"},
        "Elongation"      : {"min":  17.0,              "unit": "%"},
    },

    "EN-S275JR": {
        "Carbon"    : {"max": 0.21,  "unit": "%"},
        "Manganese" : {"max": 1.50,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Nitrogen"  : {"max": 0.012, "unit": "%"},
        "Yield Strength"  : {"min": 275.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 410.0, "max": 560.0, "unit": "MPa"},
        "Elongation"      : {"min":  23.0,              "unit": "%"},
    },
    "EN-S355JR": {
        "Carbon"    : {"max": 0.24,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.55,  "unit": "%"},
        "Nitrogen"  : {"max": 0.012, "unit": "%"},
        "Yield Strength"  : {"min": 355.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 470.0, "max": 630.0, "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "EN-S355J2": {
        "Carbon"    : {"max": 0.22,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.025, "unit": "%"},
        "Silicon"   : {"max": 0.55,  "unit": "%"},
        "Yield Strength"  : {"min": 355.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 470.0, "max": 630.0, "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "EN-P265GH": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.40,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.020, "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Chromium"  : {"max": 0.30,  "unit": "%"},
        "Nickel"    : {"max": 0.30,  "unit": "%"},
        "Molybdenum": {"max": 0.08,  "unit": "%"},
        "Yield Strength"  : {"min": 265.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 410.0, "max": 530.0, "unit": "MPa"},
        "Elongation"      : {"min":  23.0,              "unit": "%"},
    },
    "EN-16Mo3": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.10,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.010, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Molybdenum": {"min": 0.25, "max": 0.35, "unit": "%"},
        "Yield Strength"  : {"min": 280.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 450.0, "max": 590.0, "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "EN-13CrMo4-5": {
        "Carbon"    : {"max": 0.17,  "unit": "%"},
        "Manganese" : {"max": 0.80,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.010, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Chromium"  : {"min": 0.70, "max": 1.15, "unit": "%"},
        "Molybdenum": {"min": 0.40, "max": 0.60, "unit": "%"},
        "Yield Strength"  : {"min": 290.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 440.0, "max": 590.0, "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "EN-10297-E355": {
        "Carbon"    : {"max": 0.22,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.025, "unit": "%"},
        "Sulfur"    : {"max": 0.025, "unit": "%"},
        "Silicon"   : {"max": 0.55,  "unit": "%"},
        "Yield Strength"  : {"min": 355.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 500.0,              "unit": "MPa"},
        "Elongation"      : {"min":  20.0,              "unit": "%"},
    },

    "JIS-SS400": {
        "Carbon"    : {"max": 0.25,  "unit": "%"},
        "Manganese" : {"max": 1.50,  "unit": "%"},
        "Phosphorus": {"max": 0.050, "unit": "%"},
        "Sulfur"    : {"max": 0.050, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Yield Strength"  : {"min": 245.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 400.0, "max": 510.0, "unit": "MPa"},
        "Elongation"      : {"min":  21.0,              "unit": "%"},
    },
    "JIS-SM490": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.55,  "unit": "%"},
        "Yield Strength"  : {"min": 315.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 490.0, "max": 610.0, "unit": "MPa"},
        "Elongation"      : {"min":  17.0,              "unit": "%"},
    },
    "JIS-SGV410": {
        "Carbon"    : {"max": 0.24,  "unit": "%"},
        "Manganese" : {"max": 1.20,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Tensile Strength": {"min": 410.0,              "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "JIS-STPT370": {
        "Carbon"    : {"max": 0.25,  "unit": "%"},
        "Manganese" : {"max": 0.90,  "unit": "%"},
        "Phosphorus": {"max": 0.035, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Yield Strength"  : {"min": 215.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 370.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },
    "JIS-STFA22": {
        "Carbon"    : {"max": 0.15,  "unit": "%"},
        "Manganese" : {"max": 0.60,  "unit": "%"},
        "Phosphorus": {"max": 0.030, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.50,  "unit": "%"},
        "Chromium"  : {"min": 0.80, "max": 1.25, "unit": "%"},
        "Molybdenum": {"min": 0.44, "max": 0.65, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 415.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },

    "IS-2062-E250": {
        "Carbon"    : {"max": 0.22,  "unit": "%"},
        "Manganese" : {"max": 1.50,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.045, "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Vanadium"  : {"max": 0.10,  "unit": "%"},
        "Niobium"   : {"max": 0.05,  "unit": "%"},
        "Titanium"  : {"max": 0.05,  "unit": "%"},
        "Aluminum"  : {"min": 0.02,  "unit": "%"},
        "Nitrogen"  : {"max": 0.012, "unit": "%"},
        "Carbon Equivalent": {"max": 0.42, "unit": ""},
        "Yield Strength"  : {"min": 250.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 410.0,              "unit": "MPa"},
        "Elongation"      : {"min":  23.0,              "unit": "%"},
    },
    "IS-2062-E350": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.040, "unit": "%"},
        "Sulfur"    : {"max": 0.040, "unit": "%"},
        "Silicon"   : {"max": 0.45,  "unit": "%"},
        "Vanadium"  : {"max": 0.10,  "unit": "%"},
        "Niobium"   : {"max": 0.05,  "unit": "%"},
        "Titanium"  : {"max": 0.05,  "unit": "%"},
        "Aluminum"  : {"min": 0.02,  "unit": "%"},
        "Nitrogen"  : {"max": 0.012, "unit": "%"},
        "Carbon Equivalent": {"max": 0.42, "unit": ""},
        "Yield Strength"  : {"min": 350.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 490.0,              "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
    "IS-2002": {
        "Carbon"    : {"max": 0.25,  "unit": "%"},
        "Manganese" : {"max": 1.50,  "unit": "%"},
        "Phosphorus": {"max": 0.050, "unit": "%"},
        "Sulfur"    : {"max": 0.050, "unit": "%"},
        "Silicon"   : {"max": 0.45,  "unit": "%"},
        "Yield Strength"  : {"min": 255.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 410.0,              "unit": "MPa"},
        "Elongation"      : {"min":  26.0,              "unit": "%"},
    },
    "IS-10748-GR2": {
        "Carbon"    : {"max": 0.120, "unit": "%"},
        "Manganese" : {"max": 0.600, "unit": "%"},
        "Silicon"   : {"max": 0.400, "unit": "%"},
        "Sulfur"    : {"max": 0.040, "unit": "%"},
        "Phosphorus": {"max": 0.040, "unit": "%"},
        "Aluminum"  : {"min": 0.015, "unit": "%"},
        "Nitrogen"  : {"max": 0.012, "unit": "%"},
        "Titanium"  : {"max": 0.020, "unit": "%"},
        "Niobium"   : {"max": 0.020, "unit": "%"},
        "Vanadium"  : {"max": 0.010, "unit": "%"},
        "Carbon Equivalent": {"max": 0.40, "unit": ""},
        "Yield Strength"  : {"min": 210.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 330.0,              "unit": "MPa"},
        "Elongation"      : {"min":  28.0,              "unit": "%"},
    },

    "DIN-St37-2": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.40,  "unit": "%"},
        "Phosphorus": {"max": 0.050, "unit": "%"},
        "Sulfur"    : {"max": 0.050, "unit": "%"},
        "Silicon"   : {"max": 0.40,  "unit": "%"},
        "Yield Strength"  : {"min": 235.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 360.0, "max": 480.0, "unit": "MPa"},
        "Elongation"      : {"min":  25.0,              "unit": "%"},
    },
    "DIN-St52-3": {
        "Carbon"    : {"max": 0.22,  "unit": "%"},
        "Manganese" : {"max": 1.60,  "unit": "%"},
        "Phosphorus": {"max": 0.040, "unit": "%"},
        "Sulfur"    : {"max": 0.040, "unit": "%"},
        "Silicon"   : {"max": 0.55,  "unit": "%"},
        "Yield Strength"  : {"min": 355.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 490.0,              "unit": "MPa"},
        "Elongation"      : {"min":  20.0,              "unit": "%"},
    },
    "DIN-15Mo3": {
        "Carbon"    : {"max": 0.20,  "unit": "%"},
        "Manganese" : {"max": 1.10,  "unit": "%"},
        "Phosphorus": {"max": 0.040, "unit": "%"},
        "Sulfur"    : {"max": 0.040, "unit": "%"},
        "Silicon"   : {"max": 0.35,  "unit": "%"},
        "Molybdenum": {"min": 0.25, "max": 0.35, "unit": "%"},
        "Yield Strength"  : {"min": 270.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 440.0, "max": 570.0, "unit": "MPa"},
        "Elongation"      : {"min":  22.0,              "unit": "%"},
    },
}

STAINLESS_STEEL_STANDARDS = {

    "A240-304": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 18.0, "max": 20.0, "unit": "%"},
        "Nickel"    : {"min": 8.0,  "max": 10.5, "unit": "%"},
        "Nitrogen"  : {"max": 0.10,  "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 515.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "A240-304L": {
        "Carbon"    : {"max": 0.030, "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 18.0, "max": 20.0, "unit": "%"},
        "Nickel"    : {"min": 8.0,  "max": 12.0, "unit": "%"},
        "Nitrogen"  : {"max": 0.10,  "unit": "%"},
        "Yield Strength"  : {"min": 170.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 485.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "A240-316": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 16.0, "max": 18.0, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 14.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 3.00, "unit": "%"},
        "Nitrogen"  : {"max": 0.10,  "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 515.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "A240-316L": {
        "Carbon"    : {"max": 0.030, "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 16.0, "max": 18.0, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 14.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 3.00, "unit": "%"},
        "Nitrogen"  : {"max": 0.10,  "unit": "%"},
        "Yield Strength"  : {"min": 170.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 485.0,              "unit": "MPa"},
        "Elongation"      : {"min":  30.0,              "unit": "%"},
    },
    "A240-321": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 17.0, "max": 19.0, "unit": "%"},
        "Nickel"    : {"min": 9.0,  "max": 12.0, "unit": "%"},
        "Titanium"  : {"min": 0.70,              "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 515.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "A240-347": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 0.75,  "unit": "%"},
        "Chromium"  : {"min": 17.0, "max": 19.0, "unit": "%"},
        "Nickel"    : {"min": 9.0,  "max": 13.0, "unit": "%"},
        "Niobium"   : {"min": 0.10,              "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 515.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "A240-904L": {
        "Carbon"    : {"max": 0.020, "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.035, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 19.0, "max": 23.0, "unit": "%"},
        "Nickel"    : {"min": 23.0, "max": 28.0, "unit": "%"},
        "Molybdenum": {"min": 4.00, "max": 5.00, "unit": "%"},
        "Copper"    : {"min": 1.00, "max": 2.00, "unit": "%"},
        "Yield Strength"  : {"min": 220.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 490.0,              "unit": "MPa"},
        "Elongation"      : {"min":  35.0,              "unit": "%"},
    },

    "EN-1.4301": {
        "Carbon"    : {"max": 0.07,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.015, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 17.5, "max": 19.5, "unit": "%"},
        "Nickel"    : {"min": 8.0,  "max": 10.5, "unit": "%"},
        "Nitrogen"  : {"max": 0.11,  "unit": "%"},
        "Yield Strength"  : {"min": 210.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 520.0,              "unit": "MPa"},
        "Elongation"      : {"min":  45.0,              "unit": "%"},
    },
    "EN-1.4401": {
        "Carbon"    : {"max": 0.07,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.015, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 16.5, "max": 18.5, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 13.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 2.50, "unit": "%"},
        "Yield Strength"  : {"min": 210.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 520.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "EN-1.4404": {
        "Carbon"    : {"max": 0.030, "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.015, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 16.5, "max": 18.5, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 13.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 2.50, "unit": "%"},
        "Yield Strength"  : {"min": 170.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 485.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "EN-1.4541": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.015, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 17.0, "max": 19.0, "unit": "%"},
        "Nickel"    : {"min": 9.0,  "max": 12.0, "unit": "%"},
        "Titanium"  : {"min": 0.70,              "unit": "%"},
        "Yield Strength"  : {"min": 210.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 520.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },

    "JIS-SUS304": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 18.0, "max": 20.0, "unit": "%"},
        "Nickel"    : {"min": 8.0,  "max": 10.5, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 520.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "JIS-SUS316": {
        "Carbon"    : {"max": 0.08,  "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 16.0, "max": 18.0, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 14.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 3.00, "unit": "%"},
        "Yield Strength"  : {"min": 205.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 520.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
    "JIS-SUS316L": {
        "Carbon"    : {"max": 0.030, "unit": "%"},
        "Manganese" : {"max": 2.00,  "unit": "%"},
        "Phosphorus": {"max": 0.045, "unit": "%"},
        "Sulfur"    : {"max": 0.030, "unit": "%"},
        "Silicon"   : {"max": 1.00,  "unit": "%"},
        "Chromium"  : {"min": 16.0, "max": 18.0, "unit": "%"},
        "Nickel"    : {"min": 10.0, "max": 14.0, "unit": "%"},
        "Molybdenum": {"min": 2.00, "max": 3.00, "unit": "%"},
        "Yield Strength"  : {"min": 175.0,              "unit": "MPa"},
        "Tensile Strength": {"min": 480.0,              "unit": "MPa"},
        "Elongation"      : {"min":  40.0,              "unit": "%"},
    },
}

TITANIUM_STANDARDS = {

    "ASTM-Ti-Grade1": {
        "Iron"    : {"max": 0.20,  "unit": "%"},
        "Oxygen"  : {"max": 0.18,  "unit": "%"},
        "Carbon"  : {"max": 0.08,  "unit": "%"},
        "Nitrogen": {"max": 0.03,  "unit": "%"},
        "Hydrogen": {"max": 0.015, "unit": "%"},
        "Ti"      : {"min": 99.0,  "unit": "%"},
    },
    "ASTM-Ti-Grade2": {
        "Iron"    : {"max": 0.30,  "unit": "%"},
        "Oxygen"  : {"max": 0.25,  "unit": "%"},
        "Carbon"  : {"max": 0.08,  "unit": "%"},
        "Nitrogen": {"max": 0.03,  "unit": "%"},
        "Hydrogen": {"max": 0.015, "unit": "%"},
        "Ti"      : {"min": 99.0,  "unit": "%"},
    },
    "ASTM-Ti-Grade5": {
        "Aluminum": {"min": 5.50, "max": 6.75, "unit": "%"},
        "Vanadium": {"min": 3.50, "max": 4.50, "unit": "%"},
        "Iron"    : {"max": 0.40,              "unit": "%"},
        "Oxygen"  : {"max": 0.20,              "unit": "%"},
        "Carbon"  : {"max": 0.08,              "unit": "%"},
        "Nitrogen": {"max": 0.05,              "unit": "%"},
        "Hydrogen": {"max": 0.015,             "unit": "%"},
        "Ti"      : {"min": 87.0,              "unit": "%"},
    },
}

NICKEL_ALLOY_STANDARDS = {

    "Inconel-625": {
        "Nickel"    : {"min": 58.0,              "unit": "%"},
        "Chromium"  : {"min": 20.0, "max": 23.0, "unit": "%"},
        "Molybdenum": {"min": 8.0,  "max": 10.0, "unit": "%"},
        "Niobium"   : {"min": 3.15, "max": 4.15, "unit": "%"},
        "Iron"      : {"max": 5.0,               "unit": "%"},
        "Carbon"    : {"max": 0.10,              "unit": "%"},
        "Manganese" : {"max": 0.50,              "unit": "%"},
        "Silicon"   : {"max": 0.50,              "unit": "%"},
    },
    "Inconel-718": {
        "Nickel"    : {"min": 50.0, "max": 55.0, "unit": "%"},
        "Chromium"  : {"min": 17.0, "max": 21.0, "unit": "%"},
        "Molybdenum": {"min": 2.80, "max": 3.30, "unit": "%"},
        "Niobium"   : {"min": 4.75, "max": 5.50, "unit": "%"},
        "Iron"      : {"min": 17.0,              "unit": "%"},
        "Aluminum"  : {"min": 0.20, "max": 0.80, "unit": "%"},
        "Titanium"  : {"min": 0.65, "max": 1.15, "unit": "%"},
        "Carbon"    : {"max": 0.08,              "unit": "%"},
    },
    "Hastelloy-C276": {
        "Nickel"    : {"min": 57.0,              "unit": "%"},
        "Chromium"  : {"min": 14.5, "max": 16.5, "unit": "%"},
        "Molybdenum": {"min": 15.0, "max": 17.0, "unit": "%"},
        "Tungsten"  : {"min": 3.00, "max": 4.50, "unit": "%"},
        "Iron"      : {"max": 7.0,               "unit": "%"},
        "Carbon"    : {"max": 0.01,              "unit": "%"},
        "Manganese" : {"max": 1.00,              "unit": "%"},
        "Silicon"   : {"max": 0.08,              "unit": "%"},
    },
    "Monel-400": {
        "Nickel"    : {"min": 63.0,              "unit": "%"},
        "Copper"    : {"min": 28.0, "max": 34.0, "unit": "%"},
        "Iron"      : {"max": 2.50,              "unit": "%"},
        "Manganese" : {"max": 2.00,              "unit": "%"},
        "Carbon"    : {"max": 0.30,              "unit": "%"},
        "Silicon"   : {"max": 0.50,              "unit": "%"},
        "Sulfur"    : {"max": 0.024,             "unit": "%"},
    },
}

COPPER_ALLOY_STANDARDS = {

    "C11000": {
        "Copper": {"min": 99.90, "unit": "%"},
        "Oxygen": {"max": 0.040, "unit": "%"},
    },
    "C26000": {
        "Copper": {"min": 68.5, "max": 71.5, "unit": "%"},
        "Zinc"  : {"min": 28.5,              "unit": "%"},
        "Lead"  : {"max": 0.07,              "unit": "%"},
        "Iron"  : {"max": 0.05,              "unit": "%"},
    },
    "C51000": {
        "Copper"    : {"min": 94.0,              "unit": "%"},
        "Tin"       : {"min": 4.20, "max": 5.80, "unit": "%"},
        "Phosphorus": {"min": 0.03, "max": 0.35, "unit": "%"},
        "Lead"      : {"max": 0.05,              "unit": "%"},
        "Zinc"      : {"max": 0.30,              "unit": "%"},
        "Iron"      : {"max": 0.10,              "unit": "%"},
    },
}

ALL_STANDARDS = {
    **ALUMINUM_STANDARDS,
    **CARBON_STEEL_STANDARDS,
    **STAINLESS_STEEL_STANDARDS,
    **TITANIUM_STANDARDS,
    **NICKEL_ALLOY_STANDARDS,
    **COPPER_ALLOY_STANDARDS,
}

ASTM_STANDARDS = ALL_STANDARDS

def get_standard(grade: str) -> dict:
    return ALL_STANDARDS.get(grade, {})

def get_family(grade: str) -> str:
    if grade in ALUMINUM_STANDARDS:
        return "Aluminum"
    if grade in CARBON_STEEL_STANDARDS:
        return "Carbon Steel"
    if grade in STAINLESS_STEEL_STANDARDS:
        return "Stainless Steel"
    if grade in TITANIUM_STANDARDS:
        return "Titanium"
    if grade in NICKEL_ALLOY_STANDARDS:
        return "Nickel Alloy"
    if grade in COPPER_ALLOY_STANDARDS:
        return "Copper Alloy"
    return "Unknown"

def list_all_grades() -> list:
    return sorted(ALL_STANDARDS.keys())

def list_grades_by_family(family: str) -> list:
    mapping = {
        "Aluminum"       : ALUMINUM_STANDARDS,
        "Carbon Steel"   : CARBON_STEEL_STANDARDS,
        "Stainless Steel": STAINLESS_STEEL_STANDARDS,
        "Titanium"       : TITANIUM_STANDARDS,
        "Nickel Alloy"   : NICKEL_ALLOY_STANDARDS,
        "Copper Alloy"   : COPPER_ALLOY_STANDARDS,
    }
    return sorted(mapping.get(family, {}).keys())

def search_grade(keyword: str) -> list:
    keyword = keyword.upper()
    return [
        g for g in ALL_STANDARDS
        if keyword in g.upper()
    ]

GRADE_KEYWORDS = {

    "AA7075" : ["AA 7075", "AA-7075", "Alloy 7075", "UNS A97075",
                "EN AW-7075", "3.4365"],
    "AA6061" : ["AA 6061", "AA-6061", "Alloy 6061", "UNS A96061",
                "EN AW-6061", "3.3214"],
    "AA6063" : ["AA 6063", "AA-6063", "Alloy 6063", "UNS A96063",
                "EN AW-6063"],
    "AA2024" : ["AA 2024", "AA-2024", "Alloy 2024", "UNS A92024",
                "EN AW-2024", "3.1355"],
    "AA5052" : ["AA 5052", "AA-5052", "Alloy 5052", "UNS A95052"],
    "AA5083" : ["AA 5083", "AA-5083", "Alloy 5083", "UNS A95083",
                "EN AW-5083"],
    "AA1100" : ["AA 1100", "AA-1100", "Alloy 1100", "UNS A91100"],
    "AA3003" : ["AA 3003", "AA-3003", "Alloy 3003", "UNS A93003"],

    "SA516-70": ["SA 516 Grade 70", "SA516 Gr.70", "SA516-70",
                 "SA 516-70", "ASME SA516", "Grade 70 Carbon",
                 "SA516 Grade 70"],
    "SA516-60": ["SA 516 Grade 60", "SA516 Gr.60", "SA516-60",
                 "SA 516-60", "SA516 Grade 60"],
    "A36"     : ["ASTM A36", "A 36 Steel", "A-36",
                 "Structural A36"],
    "A572-50" : ["ASTM A572", "A572 Grade 50", "A572 Gr.50",
                 "A572-50"],
    "EN-10297-E355": ["EN 10297", "E355", "OVAKO 280", "OVAKO 280T"],

    "IS-2062-E250": ["IS 2062", "IS 2062_2011", "IS 2062 E250A",
                     "IS2062", "E250A", "IS-2062"],
    "IS-2062-E350": ["IS 2062 E350", "IS2062 E350",
                     "E350A", "E350BR", "IS 2062 E350A"],
    "IS-2002"     : ["IS 2002", "IS2002", "IS-2002"],
    "IS-10748-GR2": [
        "IS10748GR2", "IS 10748 GR2", "IS 10748 GR 2",
        "IS10748 Grade 2", "IS 10748 Grade 2", "IS-10748-GR2",
        "IS10748", "IS 10748", "TDCNo:TU23", "TDC TU23",
    ],
    "JIS-SS400"   : ["SS400", "SS 400", "JIS G3101", "JIS SS400"],
    "JIS-SM490"   : ["SM490", "SM 490", "JIS G3106",
                     "SM490A", "SM490B", "JIS SM490"],

    "A240-316L": ["SS 316L", "316L Stainless", "A240-316L",
                  "UNS S31603", "1.4404", "Grade 316L",
                  "Type 316L", "AISI 316L",
                  "WP316L", "A403 WP316L",                                                
                  "316L", "S31603"],                                                       
    "A240-316" : ["SS 316", "Type 316", "A240-316",
                  "UNS S31600", "1.4401", "Grade 316",
                  "AISI 316",
                  "WP316", "A403 WP316"],
    "A240-304" : ["SS 304", "Type 304", "A240-304",
                  "UNS S30400", "1.4301", "Grade 304",
                  "AISI 304",
                  "WP304", "A403 WP304"],                                                   
    "A240-304L": ["SS 304L", "Type 304L", "A240-304L",
                  "UNS S30403", "1.4307", "Grade 304L",
                  "AISI 304L",
                  "WP304L", "WP304/304L", "WP304/304L-W",                                                
                  "A403 WP304L",
                  "304L", "S30403"],                                                             
    "A240-321" : ["SS 321", "Type 321", "A240-321",
                  "UNS S32100", "1.4541", "Grade 321",
                  "AISI 321"],
    "A240-347" : ["SS 347", "Type 347", "A240-347",
                  "UNS S34700", "1.4550", "Grade 347"],

    "ASTM-Ti-Grade1": ["Titanium Grade 1", "Ti Grade 1", "Ti-1",
                       "UNS R50250", "ASTM B265 Grade 1"],
    "ASTM-Ti-Grade2": ["Titanium Grade 2", "Ti Grade 2", "Ti-2",
                       "UNS R50400", "ASTM B265 Grade 2"],
    "ASTM-Ti-Grade5": ["Ti-6Al-4V", "Ti 6Al-4V", "Grade 5 Titanium",
                       "Ti Grade 5", "UNS R56400",
                       "ASTM B265 Grade 5"],

    "Inconel-625"   : ["Inconel 625", "IN-625", "Alloy 625",
                       "UNS N06625", "2.4856", "NiCr22Mo9Nb"],
    "Inconel-718"   : ["Inconel 718", "IN-718", "Alloy 718",
                       "UNS N07718", "2.4668"],
    "Hastelloy-C276": ["Hastelloy C-276", "C-276", "Alloy C276",
                       "UNS N10276", "2.4819"],
    "Monel-400"     : ["Monel 400", "Alloy 400",
                       "UNS N04400", "2.4360"],

    "C11000"  : ["C110", "C11000", "ETP Copper",
                 "UNS C11000", "Electrolytic Copper"],
    "C26000"  : ["C260", "C26000", "Cartridge Brass",
                 "UNS C26000", "Brass 70-30"],
}

STANDARD_FAMILIES = {
    "🔵 Aluminum — ASTM/AA" : list(ALUMINUM_STANDARDS.keys())[:8],
    "🔵 Aluminum — EN"      : [k for k in ALUMINUM_STANDARDS
                                if k.startswith("EN")],
    "🔵 Aluminum — JIS"     : [k for k in ALUMINUM_STANDARDS
                                if k.startswith("JIS")],
    "🔴 Carbon Steel — ASTM": [k for k in CARBON_STEEL_STANDARDS
                                if not k.startswith(
                                    ("EN","JIS","IS","DIN"))],
    "🔴 Carbon Steel — EN"  : [k for k in CARBON_STEEL_STANDARDS
                                if k.startswith("EN")],
    "🔴 Carbon Steel — JIS" : [k for k in CARBON_STEEL_STANDARDS
                                if k.startswith("JIS")],
    "🔴 Carbon Steel — IS"  : [k for k in CARBON_STEEL_STANDARDS
                                if k.startswith("IS")],
    "🔴 Carbon Steel — DIN" : [k for k in CARBON_STEEL_STANDARDS
                                if k.startswith("DIN")],
    "⚪ Stainless — ASTM"   : [k for k in STAINLESS_STEEL_STANDARDS
                                if not k.startswith(
                                    ("EN","JIS"))],
    "⚪ Stainless — EN"     : [k for k in STAINLESS_STEEL_STANDARDS
                                if k.startswith("EN")],
    "⚪ Stainless — JIS"    : [k for k in STAINLESS_STEEL_STANDARDS
                                if k.startswith("JIS")],
    "🟡 Titanium"           : list(TITANIUM_STANDARDS.keys()),
    "🟠 Nickel Alloys"      : list(NICKEL_ALLOY_STANDARDS.keys()),
    "🟤 Copper Alloys"      : list(COPPER_ALLOY_STANDARDS.keys()),
}

if __name__ == "__main__":
    print(f"\n✅ Total Standards : {len(ALL_STANDARDS)}")
    print(f"   Aluminum       : {len(ALUMINUM_STANDARDS)}")
    print(f"   Carbon Steel   : {len(CARBON_STEEL_STANDARDS)}")
    print(f"   Stainless      : {len(STAINLESS_STEEL_STANDARDS)}")
    print(f"   Titanium       : {len(TITANIUM_STANDARDS)}")
    print(f"   Nickel Alloys  : {len(NICKEL_ALLOY_STANDARDS)}")
    print(f"   Copper Alloys  : {len(COPPER_ALLOY_STANDARDS)}")

    print(f"\n🔍 Search '316'  : {search_grade('316')}")
    print(f"🔍 get_family AA7075 : {get_family('AA7075')}")
    print(f"🔍 get_standard AA7075 Cu: "
          f"{get_standard('AA7075').get('Cu')}")